import type { GroupPage } from '$lib/config/models/types';


export const page: GroupPage = {
	id: 'beliefs',
	title: '',
	menuTitle: 'Beliefs',
	parentPath: '',
	order: 1,
	heroImage: '/beliefs/hero.jpg',
	theme: 'light',
	sections: [
	{
		id: 'core-values',
		title: 'Core Values',
		theme: 'tan',
		columns: [
			{
				title: '',
				items: [
					{
						type: 'item',
						description: 'Jesus Christ is our Lord and Savior who deserves our full love and devotion. It is the goal of every disciple to know Christ intimately and to abide in Him through obedience to His Word and dependence on His guidance.  Philippians 1:21;3:8-10; John 15:7'
					},
					{
						type: 'item',
						description: 'Life change happens best in small accountable communities where men are transparent and fully committed to Christ and each other.\nI Timothy 2:2; Colossians 3:16; James 5:16'
					},
					{
						type: 'item',
						description: 'The internalization and application of the truth of scripture to our lives is one of the principal ingredients in the renovation of the heart.\nRomans 12:2; John 8:31,32; Joshua 1:8'
					}
				]
			},
			{
				title: '',
				items: [
					{
						type: 'item',
						description: 'Our bodies are God’s dwelling place and property so it is important that we honor Him not only with morally pure lives but also through proper nutrition, exercise, and rest. I Corinthians 6:19,20;  I Timothy 4:7,8;  I Thessalonians 4:7'
					},
					{
						type: 'item',
						description: 'God has a unique mission for each Christian to fulfill in this world. This special calling of God involves reaching and discipling people in the context of the local church. The completion of our mission will only happen when our hearts, minds, and bodies are transformed by His power and fully yielded to His Spirit.\nRomans 12:1,2; 8:11; Matthew 28:18-20'
					}
				]
			}
		],
		items: [
			{
				type: 'pdf',
				title: 'Core Values PDF',
				pdf: '/about-us/beliefs/core-values.pdf'
			}
		]
	},
	{
		id: 'beliefs',
		title: 'Beliefs',
		theme: 'light',
		columns: [
			{
				title: '',
				items: [
					{
						type: 'item',
						title: 'We believe',
						description: 'the Scriptures, both Old and New Testaments, to be the inspired word of God, without error in the original writings.'
					},
					{
						type: 'item',
						title: 'We believe',
						description: 'in one God, creator of all things, infinitely perfect and eternally existing in three persons: Father, Son, and Holy Spirit.'
					},
					{
						type: 'item',
						title: 'We believe',
						description: 'Jesus Christ, became man through conception by the Holy Spirit and virgin birth; that He died on the cross, in our stead and arose from the dead.'
					},
					{
						type: 'item',
						title: 'We believe',
						description: 'that the ministry of the Holy Spirit is to glorify the Lord Jesus Christ, and during this age to convict of sin and regenerate the sinner upon believing in Christ.'
					},
					{
						type: 'item',
						title: 'We believe',
						description: 'that those who receive Jesus Christ by personal faith are born of the Holy Spirit and, thus, become children of God.'
					}
				]
			},
			{
				title: '',
				items: [
					{
						type: 'item',
						title: 'We believe',
						description: 'in the personal and imminent return of our Lord Jesus Christ.'
					},
					{
						type: 'item',
						title: 'We believe',
						description: 'in the bodily resurrection of the dead, of the believer to everlasting blessedness and joy with the Lord, and of the unbeliever to judgment and everlasting conscious punishment.'
					},
					{
						type: 'item',
						title: 'We believe',
						description: 'that the Church is composed of all persons who through saving faith in Jesus Christ have been regenerated by the Holy Spirit and are united together to the body of Christ, of which He is the head.'
					},
					{
						type: 'item',
						title: 'We believe',
						description: 'that all those who are born again by the Spirit of God should live a continual life of full devotion to Christ.'
					}
				]
			}
		]
	}
],
	heroTextColor: '',

};
